source("http://bioconductor.org/biocLite.R")
biocLite(c("GenomicRanges", "BSgenome.Hsapiens.UCSC.hg19"))
install.packages("devtools")
install.packages("ggplot2")
install.packages("Rcpp")
library(devtools)
devtools::install_github("friend1ws/pmsignature")
library(pmsignature)

inputFile <- system.file("extdata/Hoang_MFVF.ind.txt", package="pmsignature")
print(inputFile)
P<- readMFVFile(inputFile)
inputFile <- system.file("extdata/Nik_Zainal_2012.mutationPositionFormat.txt.gz", package="pmsignature")
print(inputFile)
G <- readMPFile(inputFile, numBases = 5)
Param <- getPMSignature(G, K = 3)
visPMSignature(Param, 1)
visPMSignature(Param, 2)
visPMSignature(Param, 3)
getSignatureValue(Param, 1)
getSignatureValue(Param, 2)
getSignatureValue(Param, 3)
visMembership(G, Param)
